export default [
    {
        "_id": "123",
        "topic": "Web Development",
        "username": "ReactJS",
        "liked": true,
        "disliked": false,
        "verified": false,
        "handle": "ReactJS",
        "time": "2h",
        "title": "React.js is a component based front end library that makes it very easy to build Single Page Applications or SPAs",
        "tuit": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        "video": "https://www.youtube.com/embed/unKvMC3Y1kI",
        "logo-image": "../media/react.png",
        "avatar-image": "../media/react.png",
        "comments": 123,
        "retuits": 234,
        "likes": 345,
        "dislikes": 15
    },
    {
        "_id": "567",
        "topic": "Space",
        "username": "SpaceX",
        "liked": false,
        "disliked": false,
        "verified": false,
        "handle": "spacex",
        "title": "",
        "tuit": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        "image": "../media/starship.jpg",
        "time": "last month",
        "logo-image": "../media/node.png",
        "avatar-image": "../media/node.png",
        "tuits": "120K",
        "comments": 123,
        "retuits": 234,
        "likes": 345,
        "dislikes": 15
    },
    {
        "_id": "234",
        "topic": "Space",
        "username": "Scott Manley",
        "liked": true,
        "disliked": false,
        "verified": true,
        "handle": "DJSnM",
        "postedOn": "2020-12-10",
        "time": "1 day",
        "title": "JavaScript is programming language that can run on browsers as well as desktops",
        "tuit": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        "logo-image": "../media/js.png",
        "avatar-image": "../media/js.png",
        "tuits": "123K",
        "comments": 123,
        "retuits": 234,
        "likes": 345,
        "dislikes": 15
    },
    {
        "_id": "345",
        "topic": "Web Development",
        "username": "jQuery",
        "liked": false,
        "disliked": true,
        "verified": false,
        "handle": "jQuery",
        "title": "jQuery",
        "tuit": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        "time": "last week",
        "logo-image": "../media/jq.png",
        "avatar-image": "../media/jq.png",
        "tuits": "122K",
        "comments": 123,
        "retuits": 234,
        "likes": 345,
        "dislikes": 15
    },
    {
        "_id": "456",
        "topic": "Web Development",
        "username": "NodeJS",
        "liked": true,
        "disliked": false,
        "verified": true,
        "handle": "NodeJS",
        "title": "",
        "tuit": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        "time": "last month",
        "logo-image": "../media/node.png",
        "avatar-image": "../media/node.png",
        "tuits": "120K",
        "comments": 123,
        "retuits": 234,
        "likes": 345,
        "dislikes": 15
    },
    {
        "_id": "899",
        "liked": false,
        "disliked": false,
        "verified": true,
        "handle": "nasa",
        "postedOn": "2021-12-31",
        "time": "3 months ago",
        "username": "NASA",
        "logo-image": "../media/nasa.png",
        "avatar-image": "../media/nasa.png",
        "tuit": "In 2021, our @NASAPersevere Mars rover landed",
        "comments": 123,
        "retuits": 234,
        "likes": 345,
        "dislikes": 15
    },
    {
        "_id": "344",
        "liked": false,
        "disliked": false,
        "verified": true,
        "handle": "nasa",
        "postedOn": "2022-02-04",
        "time": "1 month ago",
        "username": "NASA",
        "logo-image": "../media/nasa.png",
        "avatar-image": "../media/nasa.png",
        "tuit": "Ingenuity helicopter takes flight.",
        "comments": 123,
        "retuits": 234,
        "likes": 3468,
        "dislikes": 1
    }
];
